### ISSUE TITLE
Check for everyone's GitHub link some of the team members are not properly linked with their GitHub Acc.

### ISSUE THREAD

**Issue by Coollaitar** [pccoeacm/Anantya-2K23#61]

**Comment by Yash-Waghmare** [comment]
Describe the issue

**Comment by Coollaitar** [comment]
Check line #293[https://github.com/pccoeacm/Anantya-2K23/blob/main/src/API/TeamData.js?plain=1#L293] in the `TeamData.js` the space for GitHub link is left empty

**Comment by Yash-Waghmare** [comment]
Okay got it

**Comment by Yash-Waghmare** [comment]
Issue resolved
